name: flutter_browser
description: SearxGo — Navegador privado com SearxNG como motor de busca.

publish_to: 'none'
version: 3.1.0+9

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  flutter_inappwebview: ^6.1.5
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2
  crypto: ^3.0.5
  package_info_plus: ^8.0.2
  flutter_font_icons: ^2.2.7
  flutter_svg: ^2.0.10+1
  mime: ^1.0.6
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.1
  flutter_colorpicker: ^1.1.0
  intl: any
  uuid: ^4.5.0
  collection: any
  context_menus: ^2.0.0+1
  multi_window: ^0.2.0
  sqflite: ^2.3.3+2
  sqflite_common_ffi: ^2.3.3+1
  sqlite3_flutter_libs: ^0.5.24
  window_manager_plus: ^1.0.5
  path: any
  http: ^1.2.1
  flutter_v2ray: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.png
    - assets/images/yahoo_logo.png
    - assets/images/bing_logo.png
    - assets/images/duckduckgo_logo.png
    - assets/images/ecosia_logo.png
    - assets/icon/icon.png
